//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ModelGroup.Config
{
	namespace Resource
	{
		public enum Componets
		{
			Skeleton = 1,
			Animate = 1 << 1,
			Mesh = 1 << 2,
			Hook = 1 << 3,
			Camera = 1 << 4,
			Light = 1 << 5
		}
	}
}

