//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace ModelGroup.Config
{
	namespace Resource
	{
		internal class Param
		{
			public int nStart;
			public int nEnd;
			public Enum.Enumeration enumParam;
			
			public Param(int start, int end, Enum.Enumeration _enumParam)
			{
				nStart = start;
				nEnd = end;
				enumParam = _enumParam;
			}
		}

		public class FormatFile
		{
			private String _file;			// 文件字符串
			private List<Param> _vecParams;	// 频道使用的参数

			public FormatFile (String file)
			{
				_file = file;
				_vecParams = new List<Param> ();
			}

			private void ParseFileString()
			{
				String current = file;
				int offset = 0;

				while (true)
				{
					int start = current.IndexOf("(", offset);
					int end = current.IndexOf(")",offset);
					if (start >= 0 && end >= 0)
					{
						String param = current.Substring(start+1, end - start -1);
						Enum.Enumeration _enum = ModelFileConfig.Instance.getEnumParam(param);
						if (_enum != null){
							Param p = new Param(start, end, _enum);
							_vecParams.Add(p);
						}else{
							throw (new System.Exception("找不到参数枚举"));
						}
						offset = end+1;
					} else {
						break;
					}
				}
			}

			public Enum.Enumeration getParam(int n)
			{
				return (_vecParams != null) ? _vecParams[n].enumParam : null;
			}

			public String getFormatFile(List<uint> _params)
			{
				// todo:字符串替换 vs 字符串搜素，效率要比较后才知道。
				if (_params.Count == _vecParams.Count)
				{
					String result = file;
					for (int i = 0; i < _vecParams.Count; i++)
					{
						Param p = _vecParams[i];
						Enum.Item s = p.enumParam.getItem(_params[i]);
						if(s == null){
							return null;
						}
						result = result.Replace("(" + p.enumParam.Name + ")", s.getName(false));
					}
					return ModelFileConfig.Instance.path + result;
				}
				return null;
			}

			public int Params {
				get {return _vecParams.Count;}
			}
			public String file {
				get {return _file;}
			}
		}
	}
}

