//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ModelGroup.Config
{
	namespace Resource
	{
		public class Resource : NamedItem
		{
            static public Flags _componetsDef;
            private uint _componets;
 			private FormatFile _file;

            public Resource(String name, String alias, uint componets, String file)
				:base(name,alias)
			{
				_componets = componets;
				_file = new FormatFile (file);
			}

			public uint components
			{
				get {return _componets;}
			}
			public FormatFile file
			{
				get {return _file;}
			}
            public bool HasComponet(string c)
            {
                return _componetsDef.HasFlag(c, _componets);
            }
		}
	}
}

