//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ModelGroup.Config
{
	namespace Resource
	{
		public class Resource : NamedItem
		{
			private uint _componets;
			private FormatFile _file;

			public Resource (String name, String alias, uint componets, String file, 
			                 FormatFile.FileType type)
				:base(name,alias)
			{
				_componets = componets;
				_file = new FormatFile (file, type);
			}

			public uint components
			{
				get {return _componets;}
			}
			public FormatFile file
			{
				get {return _file;}
			}
		}
	}
}

