//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace ModelGroup
{
	namespace Resource
	{
		public class ModelGroupType : NamedItem
		{
			private List<Resource> _vecResources;

			public ModelGroupType (String name, String alias)
				:base(name,alias)
			{
				_vecResources = new List<Resource>();
			}

			public int Resources 
			{
				get {return _vecResources.Count;}
			}

			public Resource getResource(int n)
			{
				return _vecResources [n];
			}
			public void addResource(Resource r)
			{
				_vecResources.Add (r);
			}
		}
	}
}

