//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace ModelGroup.Config
{
	namespace Enum 
	{
		public class Enumeration : NamedItem
		{
			private List<Item> _listItems;
			private Dictionary<uint,Item> _dictItems;

			public Enumeration (String name,String alias)
				:base(name,alias)
			{
				_listItems = new List<Item>();
				_dictItems = new Dictionary<uint, Item> ();
			}

			public void addItem(uint id,String name,String alias)
			{
				Item item = new Item (id, name, alias);
				_listItems.Add (item);
				_dictItems [id] = item;
			}
			public Item getItem(uint id)
			{
				if (_dictItems.ContainsKey (id)) {
					return _dictItems[id];
				}
				return null;
			}
			public Item getItem(String name,bool alias)
			{
				foreach (Item item in _listItems) {
					if(item.getName(alias)==name){
						return item;
					}
				}
				return null;
			}
			public List<Item> items {
				get {return _listItems;}
			}
		}
	}
}

