//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace ModelGroup.Config
{
    public class Flags
    {
        private Dictionary<String, uint> _dictItems;

        public Flags(List<string> componets)
        {
            _dictItems = new Dictionary<string, uint>();
            int n = 0;
            foreach (string i in componets)
            {
                _dictItems[i] = (uint)(1 << n);
                n++;
            }
        }

        public uint GetBits(List<string> componets)
        {
            if (componets != null)
            {
                uint bits = 0;
                foreach (string i in componets)
                {
                    if (_dictItems.ContainsKey(i))
                    {
                        bits |= _dictItems[i];
                    }
                }
                return bits;
            }
            return 0;
        }
        public bool HasFlag(string c, uint bits)
        {
            if (_dictItems.ContainsKey(c))
            {
                uint bit = _dictItems[c];
                return (bit & bits) != 0;
            }
            return false;
        }
    }
}

