//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ModelGroup.Config
{
	public class NamedItem
	{
		private String []_name;
		public NamedItem (String name,String alias)
		{
			_name = new string[2]{name,alias};
		}

		public String getName(bool alias)
		{
			return _name [alias ? 1 : 0];
		}

		public String Name {
			get { return _name[0]; }
		}
		public String Alias{
			get { return _name [1];}
		}
	}
}

